#!/bin/bash


# rm all simdata files generated by master

echo "removing all .dat, .x[0-9]*, .t[0-9]* files"
rm `find . -name "*.dat"`
rm `find . -name "*.x[0-9]*"`
rm `find . -name "*.t[0-9]*"`

# rm all generated image files

rm `find . -name "*.eps"`
#rm `find . -name "*.png"`
